export type Request =
  | 1 // REQUEST_TYPE_PK
  | 3 // REQUEST_TYPE_JOINTEAM
  | 4 // REQUEST_TYPE_EXCAHNGECARD
  | 5 // REQUEST_TYPE_TRADE
  | 11 // REQUEST_TYPE_KICKTEAM
  | 12 // REQUEST_TYPE_LEAVETEAM
  | 13 // REQUEST_TYPE_TRADE_CONFIRM
  | 14 // REQUEST_TYPE_TRADE_REFUSE
  | 16 // REQUEST_TYPE_REBIRTH_ON
  | 17 // REQUEST_TYPE_REBIRTH_OFF

export interface IRequestApi {
  REQUEST_TYPE_PK: Request
  REQUEST_TYPE_JOINTEAM: Request
  REQUEST_TYPE_EXCAHNGECARD: Request
  REQUEST_TYPE_TRADE: Request
  REQUEST_TYPE_KICKTEAM: Request
  REQUEST_TYPE_LEAVETEAM: Request
  REQUEST_TYPE_TRADE_CONFIRM: Request
  REQUEST_TYPE_TRADE_REFUSE: Request
  REQUEST_TYPE_REBIRTH_ON: Request
  REQUEST_TYPE_REBIRTH_OFF: Request

  DoRequest: (request: Request) => void
}
